export const socialNetworks = [
  "facebook",
  "instagram",
  "twitter",
  "x",
  "linkedin",
  "youtube",
  "github",
  "pinterest",
  "tiktok",
  "snapchat",
  "telegram",
  "whatsapp",
  "discord",
  "reddit",
  "tumblr",
  "medium",
  "dribbble",
  "behance",
  "vimeo",
  "spotify",
  "soundcloud",
  "skype",
  "slack",
  "stackoverflow",
  "email",
  "rss",
  "website",
] as const

export type SocialNetwork = (typeof socialNetworks)[number]
